# config.yml
settings:
  concurrency: 50  # High concurrency for faster processing
  fetchTimeout: 3000  # Timeout for fetching M3U files
  linkCheckTimeout: 9000  # Timeout for checking link activity
  batchSize: 100  # Number of links to check in a single batch
  outputDirPrefix: SpecialLinks  # Base name for output directories/files
  channelsPerFile: 9000  # Maximum number of channels per file

urls:
- http://MyWebsitezzz.net

  # Add more URLs here (up to 100)
