name: TV-Mikhoul Update Files

on:
  push:
    branches:
      - main
      - Test-Starting-Over # Trigger on test branch
  schedule:
    - cron: '45 19 * * *' # 19:45 UTC = 15:45 EDT
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz beautifulsoup4
          
      - name: Run TV-Mikhoul M3U collector script
        run: python BugsfreeMain/TV-Mikhoul.py
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "TV-Mikhoul Update files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git push

  # update-indexes:
  #   needs: update-files
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       
  #     - name: Commit and Push Indexes
  #       run: |
  #         git config --local user.email "github-actions[bot]@users.noreply.github.com"
  #         git config --local user.name "github-actions[bot]"
  #         if [ -f "LiveTV/index.json" ]; then
  #           git add LiveTV/index.json
  #         fi
  #         if git diff --staged --quiet; then
  #           echo "No changes to commit"
  #         else
  #           git commit -m "Update LiveTV index files"
  #           git pull --rebase origin main || echo "Rebase failed, continuing"
  #           git push || echo "Push failed"
  #         fi
